name: atmos-modeling-cookbook-dev
channels:
  - conda-forge
dependencies:
  - mystmd
  - jupyter-book
  - jupyterlab
  - numpy
  - xarray
  - matplotlib
  - numba
  - cmweather
  - holoviews
  - hvplot
  - panel
